### PR TITLE
Code needs update after Vault's bug patch

### PR DESCRIPTION
**Pull request by joveice**
" StockMarket.economy.depositPlayer(this.player.getName(), -1 * amount * stock.getPrice()); "
is no longer working since its based on a bug thats now patched
the code that will work is " StockMarket.economy.withdrawPlayer(this.player.getName(), amount * stock.getPrice()); "
the plugin as it is will not charge with the old code when buying shares, tho with the new code it should charge for the shares you buy.
and it works on 1.8.8

### CODE REVIEW

**Comment by mashlol** [comment]
All these commits are my own, something isn't right here..

**Comment by joveice** [comment]
i don't know what i have to do, and this was the only thing that worked and had the name pull request in it

**Comment by mashlol** [comment]
Well you already made a fork of the repo, so here's the easiest way:

1. Navigate to your fork (https://github.com/joveice/StockMarket)
2. Update the file(s) you want to change (you can even use the GitHub UI online to do this)
3. Commit the changes (GitHub UI should prompt you at the bottom if you edit the file)
4. Submit a pull request (There should be an option to do this near the top of the page for your fork)

And that should do it.

**Comment by joveice** [comment]
So when can you release a update on the plugin? its 1.8.8 ready

**Comment by mashlol** [comment]
Closing this, the actual fix was merged in #18

**Comment by DraksterAU** [comment]
drakster2012 is the bukkitdev account name, unfortunately it uses curse :(

**Comment by mashlol** [comment]
Okay added you as a maintainer, please feel free to upload a new version w/ the updates.

**Comment by DraksterAU** [comment]
Thanks man :)

**Pull request closed without merging**
